// AUTO-GENERATED by scripts/generate-video-manifest.mjs — do not edit by hand.
// Run `npm run videos:manifest` (or `npm run build`) after adding videos to
// public/media/videos/TikTok or public/media/videos/clients.

import type { PortfolioCategory } from "@/lib/types";

export type VideoManifestEntry = {
  video_url: string;
  title: string;
  category: PortfolioCategory;
  sort_order: number;
};

export const VIDEO_MANIFEST: VideoManifestEntry[] = [
  {
    "video_url": "/media/videos/TikTok/Bad%20Edit.mp4",
    "title": "Bad Edit",
    "category": "tiktok",
    "sort_order": 0
  },
  {
    "video_url": "/media/videos/TikTok/Dangerous%20(Vmas%201995)%20Edit.mp4",
    "title": "Dangerous (Vmas 1995) Edit",
    "category": "tiktok",
    "sort_order": 1
  },
  {
    "video_url": "/media/videos/TikTok/Michael%20(The%20Movie)%20Edit.mp4",
    "title": "Michael (The Movie) Edit",
    "category": "tiktok",
    "sort_order": 2
  },
  {
    "video_url": "/media/videos/TikTok/Smooth%20Criminal%20Edit.mp4",
    "title": "Smooth Criminal Edit",
    "category": "tiktok",
    "sort_order": 3
  },
  {
    "video_url": "/media/videos/TikTok/Speed%20Demon%20Edit.mp4",
    "title": "Speed Demon Edit",
    "category": "tiktok",
    "sort_order": 4
  },
  {
    "video_url": "/media/videos/TikTok/The%20King%20Of%20Pop%20%20Edit.mp4",
    "title": "The King Of Pop  Edit",
    "category": "tiktok",
    "sort_order": 5
  },
  {
    "video_url": "/media/videos/clients/Clicks%20Just%20Made%20A%20Map.mp4",
    "title": "Clicks Just Made A Map",
    "category": "clients",
    "sort_order": 0
  },
  {
    "video_url": "/media/videos/clients/Delta%20Executor%20Tutorial.mp4",
    "title": "Delta Executor Tutorial",
    "category": "clients",
    "sort_order": 1
  },
  {
    "video_url": "/media/videos/clients/F.R.I.E.N.D.S.%20Edit.mp4",
    "title": "F.R.I.E.N.D.S. Edit",
    "category": "clients",
    "sort_order": 2
  },
  {
    "video_url": "/media/videos/clients/Ranking%20Funniest%20Big%20Cat%20Moments.mp4",
    "title": "Ranking Funniest Big Cat Moments",
    "category": "clients",
    "sort_order": 3
  },
  {
    "video_url": "/media/videos/clients/Skooby%20Edit.mp4",
    "title": "Skooby Edit",
    "category": "clients",
    "sort_order": 4
  },
  {
    "video_url": "/media/videos/clients/The%20Reason%20Why%20Your%20Family%20Hates%20You.mp4",
    "title": "The Reason Why Your Family Hates You",
    "category": "clients",
    "sort_order": 5
  },
  {
    "video_url": "/media/videos/clients/This%20Moment%20Could%20Cost%20Neymar.mp4",
    "title": "This Moment Could Cost Neymar",
    "category": "clients",
    "sort_order": 6
  },
  {
    "video_url": "/media/videos/clients/Yandere%20Simulator%20-%20Class%20of%20'59%20Trailer.mp4",
    "title": "Yandere Simulator - Class of '59 Trailer",
    "category": "clients",
    "sort_order": 7
  },
  {
    "video_url": "/media/videos/clients/Your%20Perm%20If%20You....mp4",
    "title": "Your Perm If You...",
    "category": "clients",
    "sort_order": 8
  }
];
